---
bibliography: references.bib
---
Identifying the determinants of sentiment, and examining its role in forecasting spending has long been intrigued econometricians and policy makers. While early research relied primarily on national or state-level aggregate data to examine this relationship, the field has evolved methodologically with the increasing adoption of microeconomic survey data. This methodological shift offers enhanced analytical power for assessing the predictive capacity of sentiment indicators on consumption dynamics. Our paper represents the first comprehensive attempt to examine the predictive power of sentiment on consumption growth and to test the implications of the rational expectation based Permanent Income/Life Cycle Hypothesis using household-level data from India.

To examine whether sentiment can forecast household consumption growth in India, we employ the comprehensive longitudinal microdata from the Consumer Pyramid Household Survey (CPHS). Our novel methodological approach involves constructing two distinct expenditure-minimizing consumption bundles: (i) food bundle, and (ii) food & fuel bundle. These bundles serve as household-specific real consumption expenditure measures, effectively preserving the rich cross-sectional heterogeneity of the Indian economy. We utilize two forward-looking sentiment indicators: households' expectations regarding their future financial position and their perceptions of future business conditions. By using these sentiment measures within an Euler equation framework, we simultaneously test whether household sentiment indicators possess significant predictive power for consumption growth and whether consumption exhibits excess sensitivity to sentiment fluctuations—findings that would test the validity of the Permanent Income Hypothesis (PIH) in the Indian household context.

We show that household sentiments explained by geographical location, income level, educational attainment, and demographic characteristics are superior predictors of consumption growth compared to raw sentiment itself. Our results endorse @blendon1997, who argue that an individual's neighborhood is instrumental in forming and shaping their sentiments. We also demonstrate that the fuel consumption of Indian households exhibits greater sensitivity to sentiments than food consumption. We argue that, consistent with pre-pandemic patterns, sentiments should remain crucial for business cycle forecasting in post-pandemic periods, despite COVID-19 fundamentally altering spending patterns and their underlying determinants for Indian households by exerting persistent impact on the psyche of consumers. Our results broadly parallel evidence from developed economies, contributing to the broader literature on sentiment-driven consumption and business cycle dynamics.

Finally, to outline our future research agenda, we note that the sluggish recovery pattern of consumption for Indian households depicted in  @fig-ics closely mimics the dynamics of US consumption growth in the post-Great Recession period. @pistaferri2016 demonstrates that alongside sentiments, household debt and net worth should be controlled for when explaining post-Great Recession consumption growth dynamics in the US. Depending on the availability of data, we plan to explore models that incorporate health-related risks faced by Indian households due to the COVID-19 pandemic, alongside their sentiments, liabilities, and net worth to explain the COVID-period dynamics of consumption growth for India.


