---
bibliography: references.bib
---
Rational expectations based permanent/life cycle hypothesis predicts consumption growth is random, and unpredictable, implying the information about the current consumption possesses all the relevant information to predict consumption growth. Literature tests this hypothesis for the developed countries with aggregate data, and find evidence against it. Existing literature further shows that, aggregate sentiments is important, and captures additional information beyond that in the current consumption to predict consumption growth. @souleles_expectations_2004 tests the PIH using household level data of the US, and he also finds presence of excess sensitivity of consumption to their sentiments for the US. Alongside the violation of the PIH, he also finds existence of the precautionary savings motive among the US households. Following @souleles_expectations_2004, our objective of this paper is to test the excess sensitivity of consumption to sentiments for India using the Euler equation approach. 

To do it, we have used the large longitudinal data given by CPHS, which is representative of the Indian economy. Alongside the household level consumption, income, and demographic data, we also use the data of prices of different food groups, and fuel and lighting - the largest two components of household consumption for India to calculate a household level price index for India. Then, in contrary to the existing literature, instead of using the aggregate CPI, we use this household level price index to calculate real consumption and the real income of the Indian households. This allows us keeping the rich information content intact in estimation, arising from the large time-varying cross sectional heterogeneity of the micro level data. Note, using the CPHS data, @priya_sharma2024 have estimated the consumption function for Indian households using the data of the household level sentiments to test the presence of animal spirits, and it's role in the propagation of the oil price shock. Our paper on the other hand, is the first attempt to test the rational expectations based PIH using the household level data for India.    

Like the US, our paper finds the presence of the excess sensitivity of consumption to sentiments for the Indian households. It further shows that the household sentiments are important to forecast the consumption growth for Indian as well. Our results imply, like the US, PIH does not hold for India as well. To test the robustness of our results, following @souleles_expectations_2004, we also control for the household specific forecast errors in our estimation to eliminate the possibility of the endogeneity and the consequent spurious excess sensitivity. We find that, the spurious excess sensitivity does not exists in our estimation. Absence of spurious excess sensitivity shows that, the excess sensitivity of consumption to sentiments found by us for India is robust. Note, the consumption of foods and fuel used in our estimation holds approximately 92% of household consumption of India. Our results imply that, household sentiments, and the significant information content embedded in the time-varying cross sectional heterogeneity of the micro-level data intact as much as possible in estimation, if we need to appropriately forecast consumption growth for the Indian households. 
