---
bibliography: references.bib
---
The Canonical permanent income/life cycle hypothesis (PIH) predicts consumption as a random walk process, whose growth rate is unpredictable [see, @hall1978]. This implies, only current consumption captures all available information to predict the future consumption. However, as soon as the survey data of consumer sentiments become available, a large body of literature starts using sentiments to test the implications of PIH. While doing it, their primary objective was to test if sentiments possess additional information, beyond that in the current consumption, which helps predicting the future consumption, and if so why? 

Using the Euler equation framework, @carroll_does_1994 finds lagged sentiments (measured by the Index of Consumer Sentiments, ICS) positively affects the consumption growth rate of the US. @carroll_does_1994 explains the excess sensitivity of consumption to the lagged sentiments by means of consumption frictions; arising primarily from the habit formation of the individuals. @acemoglou1994 find the excess sensitivity of consumption to sentiments, and the violation of the PIH for the UK. They explain the positive relationship between consumer confidence and consumption through the precautionary savings motive of the individuals. They show that, the higher consumer confidence is not only associated with average income, but is is also associated with the uncertainty, arising from the higher income volatility. According to @acemoglou1994, such a positive association between the sentiments, and uncertainty induces the individuals to save more, yielding the positive relationship between consumer confidence, and the consumption growth as observed in their estimation.

Observing the importance of sentiments in forecasting consumption growth, a growing number of literature studies it's determinants. While, analyzing the determinants of household sentiments, @blendon1997 finds that the household sentiments is not necessarily a mirror image of current macroeconomic conditions because individuals often form their sentiments during the discussion with their neighbor at the backyard of their apartment. @lahiri_determinants_2016 performed a detailed analysis of ICS, and it's underlying sub-components. They find, household sentiments, mostly driven by the perceptions of their own financial conditions, and unemployment contains significant information, which is highly heterogeneous, asymmetric, and cyclical in nature. They also argued that, such a rich important information content, embodied in household sentiments are often lost in aggregation. Additionally, @lahiri_forecasting_2016 shows that, the time-varying asymmetry in the cross sectional distribution of household's expected financial condition, unemployment, and non-economic wave of optimism and pessimism cause household sentiments significant in forecasting consumption growth. 

@souleles_expectations_2004 also highlights the importance of the household level information sets, and expectations while testing the implications of rational forecasts by directly using the household level data of sentiments for the US. Alongside the rational expectations, the paper also tests the excess sensitivity of consumption to sentiments for the US households through an Euler equation framework. Note, the Euler equation framework not only tests the excess sensitivity of consumption to sentiments, but it also gives us natural setting to test the validity of the PIH by using the highly informative micro level data of the household sentiments as already identified in the literature, discussed above. Note, @souleles_expectations_2004 sourced the data of household sentiments, and consumption from two different surveys for his estimation. While, the data of household sentiments are taken from CAB, the data of household consumption are obtained from CEX. @souleles_expectations_2004 first matched these two datasets through a rich set of the demographic characteristics of the households, and consequently used their estimated sentiments as one of the control variables in his estimation. As a result, @souleles_expectations_2004 had to use a two-sample instrumental variables technique to obtain a correctly adjusted standard error of the coefficient of the estimated sentiments. The paper finds that, the excess sensitivity of consumption to sentiments holds, and hence PIH is violated for the US. The paper also finds the evidence of the precautionary savings motive for the US households. @souleles_expectations_2004 established the robustness of their results by including households estimated forecast errors as an additional control variables to the log-linearized Euler equation alongside the sentiments, which eliminates the possibility of the spurious excess sensitivity.

The extant literature has already identified that, the cross sectional heterogeneity of the micro level data contains important information, which gets lost in aggregation. @lahiri_determinants_2016, and @souleles_expectations_2004 identified the importance of household level sentiments for predicting consumption growth of the US. In this context, it is important to note, India is a big country, and the extent of demographic diversities of the country are significantly higher than that of any developed country. As a result, using the household level sentiments obtained from the CPHS, CMIE, we examine the excess sensitivity of consumption to sentiments, and the validity of the PIH for India by fully utilizing the large informative content of the Indian data. In this context, it important to note that a few papers have used the data of sentiments provided by CPHS, CMIE to estimate a consumption function for the Indian households. The main objective of the papers to test the presence of animal spirits, and its role in the propagation of the oil price and the monetary policy shock to consumption [see, @priya_sharma2024]. Our paper is the first genuine attempt to examine the presence of the excess sensitivity of consumption to sentiments for the India households. We have employed an Euler equation approach for estimation so that we can simultaneously test the PIH for the Indian households along with the role of sentiments in the prediction of household level consumption of India. 

It is important to note that, we lose a significant extent of cross sectional heterogeneity when, following the existing literature, we calculate the household level real consumption, and income by deflating their corresponding nominal consumption, and the nominal income through an aggregate CPI. We find that, the incidence of inflation considerably differs across households, influencing their demand for goods and services. As a result, instead of using an aggregate price index, a household specific price index is required for calculating real income, and consumption to preserve the cross sectional heterogeneity, and the associated information content of the data. Hence, we calculate an expenditure minimizing consumption bundle for each Indian household by deflating their nominal consumption, and income through a household specific price index, and used it in our analysis. Following this methodology, we calculate two types of consumption bundles for the Indian households - (i) the consumption bundles consisting of only 8 important food groups, and (ii) the consumption bundle that includes fuel and lighting along with the 8 important food groups. Using these consumption bundles, we examine the excess sensitivity of consumption to sentiments for the India households through the Euler equation approach as done by @souleles_expectations_2004 for the US. 

Note, unlike @souleles_expectations_2004, we obtain the data of household consumption, income, sentiments, and other relevant demographic characteristics from a single survey - CPHS, CMIE for India. It gives a large longitudinal data household consumption, sentiments, income, and other relevant demographic variable, which is representative of the Indian economy.  As a result, instead of using the two sample instrumental variables technique, we have used GMM in our paper. Note, the GMM estimation used by us, where the part of the household sentiments explained by their income, and other demographic characteristics as suggested by @souleles_expectations_2004 is used as an excess sensitivity regressor for estimation is identical in spirit with the two sample instrumental variables technique used by @souleles_expectations_2004. It is also important to mention here that, we have also performed a baseline OLS estimation to test the excess sensitivity of consumption to sentiments where, unlike the GMM, we directly use the raw household sentiments entered in the regression equation. We find that, the impact of sentiments on consumption growth is significantly higher under GMM than that of OLS. This implies that, the part of the sentiments, explained by the income, and other relevant demographic characteristics of the Indian households is a better predictor of their consumption growth than the raw sentiments itself.


We have used two types of household sentiments as the excess sensitivity regressors in our paper - (i) the perception of the households about their own year ahead financial position, and (ii) the perception of the households regarding the year ahead business condition. Moreover, to eliminate the possibility of the spurious excess sensitivity, we have also controlled the household's forecast error related to their own financial position, alongside the household sentiments, and their demographic characteristics as suggested by @souleles_expectations_2004. We find, like the US, the excess sensitivity of consumption to sentiments exists for India. This implies that the household sentiments of India holds important information, beyond that in current consumption that helps predicting their future consumption. This further implies that, PIH does not hold for India. Our results also show - (i) since the sentiments of the households are associated with uncertainty, the motive of precautionary savings also exists for the Indian households, and (ii) fuel and lighting is an important component of the consumption of Indian households. The prediction of consumption growth by sentiments significantly rises once we include fuel and lighting in the consumption bundle of the household along with the food groups. 
